function [prl_ERT] = signalSaver...
    ( ...
    cue_signals, ...
    cRew_signals, ...
    cNoRew_signals, ...
    iRew_signals, ...
    iNoRew_signals, ...
    prl_phase, ...
    treatment ...
    )

prl_ERT.(prl_phase).(treatment).cue = cue_signals;
prl_ERT.(prl_phase).(treatment).cRew = cRew_signals;
prl_ERT.(prl_phase).(treatment).cNoRew = cNoRew_signals;
prl_ERT.(prl_phase).(treatment).iRew = iRew_signals;
prl_ERT.(prl_phase).(treatment).iNoRew = iNoRew_signals;
end